baseURL = 'https://luosua.github.io/portfolio/'
languageCode = 'en-us'
title = 'Alona Liuzniak Portfolio'


[module]
[module.hugoVersion]
# We use hugo.Deps to list dependencies, which was added in Hugo 0.92.0
min = "0.92.0"

[[module.imports]]
path="github.com/zetxek/adritian-free-hugo-theme"

# The following mounts are required for the theme to be able to load bootstrap
# Remember also to copy the theme's `package.json` to your site, and run `npm install`

 [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "static"
    target = "static"


[[module.mounts]]
  source = "node_modules/bootstrap/scss"
  target = "assets/scss/bootstrap"

[[module.mounts]]
  source = "node_modules/bootstrap/dist/js"
  target = "assets/js/bootstrap"

[[module.mounts]]
  source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
  target = "assets/js/vendor/bootstrap.bundle.min.js"


[params]

  title = 'Alona Liuzniak | AI Developer | Generative AI & Chatbot Solutions | Responsible AI Expert'
  description = ''
  images = ['/img/og-img.png']
  sections = ["showcase", "about", "experience", "client-and-work", "education", "certifications", "publications", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 2

  [params.analytics]
  ## Analytics parameters.
  ### Supported so far: Vercel (Page Insights, Analytics)
  ### And Google (Tag Manager, Analytics)

  # controls vercel page insights - disabled by default
  # to enable, just set to true
  vercelPageInsights = false
  vercelAnalytics = false

  # google analytics and tag manager. to enable, set "enabled" to true
  # and add the tracking code (UA-something for analytics, GTM-something for tag manager)
  [params.analytics.googleAnalytics]
      code = "UA-XXXXX-Y"
      enabled = false
  [params.analytics.googleTagManager]
      code = "GTM-XXXXX"
      enabled = false

[build]
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = true

[params.languages.selector.disable]
  footer = false

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en'
    languageDirection = 'ltr'
    languageName = 'English'
    title = ''
    weight = 0

    [languages.en.menus]

      [[languages.en.menus.header]]
        name = "Experience"
        URL = "#experience"
        weight = 2
      [[languages.en.menus.header]]
        name = 'Portfolio'
        URL = '#portfolio'
        weight = 3

      [[languages.en.menus.header]]
        name = 'Education'
        URL = '#education'
        weight = 4
      [[languages.en.menus.header]]
        name = 'Publications'
        URL = '#publications'
        weight = 5
      [[languages.en.menus.header]]
        name = 'Testimonials'
        URL = '#testimonial'
        weight = 6
      [[languages.en.menus.header]]
        name = "Contact"
        URL = "#contact"
        weight = 7

      [[languages.en.menus.footer]]
        name = "Impressum"
        URL = "/impressum/"
        weight = 1
      [[languages.en.menus.footer]]
        name = "Datenschutz"
        URL = "/datenschutz/"
        weight = 2


  [languages.de]
    disabled = false
    languageCode = 'de'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = ''
    weight = 0

    [languages.de.menus]

      [[languages.de.menus.header]]
        name = "Erfahrung"
        URL = "de/#experience"
        weight = 2
      [[languages.de.menus.header]]
        name = 'Portfolio'
        URL = 'de/#portfolio'
        weight = 3

      [[languages.de.menus.header]]
        name = 'Bildungsweg'
        URL = 'de/#education'
        weight = 4
      [[languages.de.menus.header]]
        name = 'Publikationen'
        URL = 'de/#publications'
        weight = 5
      [[languages.de.menus.header]]
        name = 'Empfehlungen'
        URL = 'de/#testimonial'
        weight = 6
      [[languages.de.menus.header]]
        name = "Kontakt"
        URL = "de/#contact"
        weight = 7

      [[languages.de.menus.footer]]
        name = "Impressum"
        URL = "/impressum/"
        weight = 1
      [[languages.de.menus.footer]]
        name = "Datenschutz"
        URL = "/datenschutz/"
        weight = 2

  [languages.it]
    disabled = false
    languageCode = 'it'
    languageDirection = 'ltr'
    languageName = 'Italiano'
    title = ''
    weight = 0

    [languages.it.menus]
      [[languages.it.menus.header]]
        name = "Esperienza"
        URL = "it/#experience"
        weight = 2
      [[languages.it.menus.header]]
        name = 'Portfolio'
        URL = 'it/#portfolio'
        weight = 3

      [[languages.it.menus.header]]
        name = 'Formazione'
        URL = 'it/#education'
        weight = 4
      [[languages.it.menus.header]]
        name = 'Pubblicazioni'
        URL = 'it/#publications'
        weight = 5
      [[languages.it.menus.header]]
        name = 'Testimonianze'
        URL = 'it/#testimonial'
        weight = 6
      [[languages.it.menus.header]]
        name = "Contattare"
        URL = "it/#contact"
        weight = 7

      [[languages.it.menus.footer]]
        name = "Impressum"
        URL = "/impressum/"
        weight = 1
      [[languages.it.menus.footer]]
        name = "Datenschutz"
        URL = "/datenschutz/"
        weight = 2


# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/custom.css"
  [[params.plugins.css]]
  URL = "css/adritian-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"

  # SCSS Plugins
  [[params.plugins.scss]]
  URL = "scss/adritian.scss"


# theme/color style
[params.colorTheme]

## the following configuration would disable automatic theme selection
#  [params.colorTheme.auto]
#    disable = true
#  [params.colorTheme.forced]
#    theme = "dark"

## the following parameter will disable theme override in the footer
#  [params.colorTheme.selector.disable]
#  footer = true


## by default we allow override AND automatic selection

[params.blog]
layout = "default" # options: default, sidebar
sidebarWidth = "25" # percentage width of the sidebar
showCategories = true
showRecentPosts = true
recentPostCount = 5
listStyle = "summary" # options: simple, summary
relativeURLs = true
canonifyURLs = true
